import React from 'react';
import MovieCard, { IMovieCard } from '@/components/MovieHomepage/MovieCard';
import Paginate from '@/components/MovieHomepage/Paginate';
import type { Metadata, ResolvingMetadata } from 'next';
type Props = {
  searchParams?: {
    page?: number;
  };
};
export const metadata: Metadata = {
  title: 'Movie Friends App 2023 | Top Rated',
  description: 'Generated by create next app'
};
async function getTopRatedMovies(page: number) {
  const res = await fetch(
    `https://api.themoviedb.org/3/movie/top_rated?api_key=${process.env.NEXT_API_KEY}&language=en-US&page=${page}`
  );
  return res.json();
}

const page = async ({ searchParams }: Props) => {
  const page = searchParams?.page || 1;

  const topRatedMovies = await getTopRatedMovies(page);

  return (
    <main className="flex flex-col mt-6">
      <div className="w-[1276px] mx-auto flex justify-between items-center mt-10 mb-4">
        <h1 className="text-2xl font-medium">Top Rated Movies</h1>
      </div>
      <div className="w-[1330px] max-w-full px-4 mx-auto">
        <div className="mt-5 grid grid-cols-2 justify-items-center gap-x-2 gap-y-4 md:grid-cols-3 lg:grid-cols-4 lg:gap-x-3 lg:gap-y-3">
          {topRatedMovies.results.map((movie: IMovieCard) => (
            <MovieCard key={movie?.id} movie={movie} />
          ))}
        </div>
      </div>
      <Paginate
        currentPage={page < 1 || page > topRatedMovies.total_pages ? 1 : page}
        totalPages={topRatedMovies.total_pages}
        pageType="top-rated"
      />
    </main>
  );
};

export default page;
